{% set name = "spiceypy" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../SpiceyPy

  patches:
    - 0001-Remove-CSPICE-installation-logic.patch
    - 0002-Get-rid-of-setup_requires.patch

build:
  number: 0
  noarch: python

  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - _libgcc_mutex 0.1 main
    - ca-certificates 2019.11.28 hecc5488_0
    - certifi 2019.11.28 py27_0
    - libffi 3.2.1 he1b5a44_1006
    - libgcc-ng 9.2.0 hdf63c60_0
    - libstdcxx-ng 9.2.0 hdf63c60_0
    - ncurses 6.1 hf484d3e_1002
    - openssl 1.1.1d h516909a_0
    - pip 19.3.1 py27_0
    - python 2.7.15 h5a48372_1009
    - readline 8.0 hf8c457e_0
    - setuptools 42.0.2 py27_0
    - sqlite 3.30.1 hcee41ef_0
    - tk 8.6.10 hed695b0_0
    - wheel 0.33.6 py27_0
    - zlib 1.2.11 h516909a_1006
  run:
    - python
    - cspice ==66
    - numpy
    - six

test:
  imports:
    - spiceypy
    - spiceypy.utils
  requires:
    - pytest
    - pandas
    - numpy
  source_files:
    - spiceypy/tests
  commands:
    - python -m pytest spiceypy -rpP -v --verbose --tb=long

about:
  home: https://github.com/AndrewAnnex/SpiceyPy
  license: MIT
  license_file: LICENSE
  summary: 'The NASA JPL NAIF SPICE toolkit wrapper written in Python'

  description: |
      SpiceyPy is a python wrapper for the SPICE Toolkit. SPICE is an
      essential tool for scientists and engineers alike in the planetary
      science field for Solar System Geometry.
  doc_url: http://spiceypy.readthedocs.io/

extra:
  recipe-maintainers:
    - juanlu001
    - AndrewAnnex
